# Generated by Django 3.1.1 on 2020-09-06 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('box_id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('box_location', models.CharField(max_length=300)),
                ('box_description', models.CharField(max_length=300)),
                ('other_box_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_desc', models.CharField(max_length=500)),
                ('item_img', models.CharField(max_length=50)),
                ('item_value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('keyword_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_title', models.CharField(max_length=50)),
                ('staff_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_loc', models.CharField(max_length=200)),
                ('warehouse_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords_in_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.items')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Items_in_boxes',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField(default=datetime.date.today)),
                ('date_to', models.DateField(blank=True)),
                ('reason', models.CharField(max_length=100)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.boxes')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.items')),
                ('moved_by_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.staff')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='item_owner_staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.staff'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_date', models.DateField(default=datetime.date.today)),
                ('inv_comment', models.CharField(max_length=500)),
                ('inv_box', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inv.boxes')),
                ('inv_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inv.items')),
                ('inv_warehouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inv.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='boxes',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.warehouse'),
        ),
    ]
