# Generated by Django 3.1.1 on 2020-09-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='box_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
