# Generated by Django 3.1.1 on 2020-09-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20200906_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxes',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='items_in_boxes',
            options={'verbose_name_plural': 'Items in Boxes'},
        ),
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='keywords_in_items',
            options={'verbose_name_plural': 'Keywords in Items'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'Warehouses'},
        ),
    ]
