# Generated by Django 3.1.1 on 2020-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_items_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_qty',
            field=models.IntegerField(default='1'),
        ),
    ]
