# Generated by Django 3.1.1 on 2020-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20200906_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='box_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='box_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='other_box_details',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_desc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_img',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='keyword_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_details',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_loc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
