# Generated by Django 3.1.1 on 2020-09-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20200906_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_in_boxes',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
