# Generated by Django 3.1.1 on 2020-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20200906_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
