# Generated by Django 3.1.1 on 2020-09-16 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_auto_20200908_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_remaining',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Percent Remaining'),
        ),
    ]
