# Generated by Django 3.1.1 on 2020-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_auto_20200916_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='box_img',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_img',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
