# Generated by Django 3.1.1 on 2020-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0012_auto_20200917_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='box_img',
            field=models.CharField(blank=True, default='box.png', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_img',
            field=models.CharField(blank=True, default='warehouse.png', max_length=20),
        ),
    ]
