# Generated by Django 3.1.1 on 2020-09-18 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_auto_20200917_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh', to='inv.warehouse'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_owner_staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='inv.staff'),
        ),
        migrations.AlterField(
            model_name='items_in_boxes',
            name='box_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bx_id', to='inv.boxes'),
        ),
        migrations.AlterField(
            model_name='items_in_boxes',
            name='date_from',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='items_in_boxes',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itm_id', to='inv.items'),
        ),
        migrations.AlterField(
            model_name='keywords_in_items',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kw_itm', to='inv.items'),
        ),
        migrations.AlterField(
            model_name='keywords_in_items',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kw_kw', to='inv.keywords'),
        ),
    ]
