# Generated by Django 3.1.1 on 2020-09-18 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0015_auto_20200917_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_in_boxes',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
